### ISSUE TITLE
Ambient context Error

### ISSUE THREAD

**Issue by raju1014** [zefoy/ngx-ace-wrapper#13]
Hi,
I had installed the editor in to my application and i'm able to run the application but i'm getting following error. Can somebody help me on this.

![ace editor issue](https://user-images.githubusercontent.com/59191615/75328063-61af1880-58a3-11ea-8b4c-10fa9fe97397.JPG)

**Comment by raju1014** [comment]
Hi, I had removed space between get and value(getvalue()).. which has solved(not able to see error while compiling) the errors i'm facing.. please let me know whether it is correct or not...
If its correct can yo please update the package.

**Comment by MJBGO** [comment]
Hello ! I have the same problem ... TS 2.9.2.

Can it be solved ? Thanks :)

![image](https://user-images.githubusercontent.com/8344487/76683079-70b2fc00-6601-11ea-87c5-8d2fe6174fc2.png)

**Comment by MJBGO** [comment]
Hi ! Use older version of the lib if you have Typescript < 3.6 in your project ;)
