### ISSUE TITLE
Warning: Entry point 'ngx-ace-wrapper' contains deep imports

### ISSUE THREAD

**Issue by mbx2015** [zefoy/ngx-ace-wrapper#17]
`Warning: Entry point 'ngx-ace-wrapper' contains deep imports into 'C:/Users/XXX/fc_5/node_modules/brace/mode/text', 'C:/Users/XXX/fc_5/node_modules/brace/theme/github'. This is probably not a problem, but may cause the compilation of entry points to be out of order.`

**Comment by asleire** [comment]
What does the "invalid" label mean? I get this warning too with version 10.0.1 and angular version 10.1.5
