### ISSUE TITLE
Directive mode doesn't work

### ISSUE THREAD

**Issue by CarterLi** [zefoy/ngx-ace-wrapper#2]
```html
<div [ace] mode="json" readonly [(text)]="this.JSON"></div>
```

I got

```
index.ts:28 Error: Template parse errors:
Can't bind to 'text' since it isn't a known property of 'div'. ("detail-json font-mono" *ngIf="this.record.showDetail === 'JSON'">
  <div [ace] mode="json" readonly [ERROR ->][(text)]="this.JSON"></div>
</div>
```

I can't find property named `text` in <https://github.com/zefoy/ngx-ace-wrapper/blob/master/src/lib/ace.directive.ts#L22>, could you please have a check?

**Comment by sconix** [comment]
There is no text property neither is there readonly property.

**Comment by sconix** [comment]
With the directive you set the text inside the div and if you are looking for easy way to set ace readonly mode on then there is a disabled property that you can use.

**Comment by CarterLi** [comment]
But the doc reads:

> <div class="ace" [ace]="config" [(text)]="text"></div>

**Comment by sconix** [comment]
Thats an error, I will fix it.

**Comment by sconix** [comment]
The component name matches Angular style guide.

At least directive does not have support for textContent so its more of an questions does Ace support dynamically changing content. My guess is no.

**Comment by CarterLi** [comment]
It's not just a matter style. All custom elements are required to have a dash in their tag name.

https://stackoverflow.com/questions/22545621/do-custom-elements-require-a-dash-in-their-name
