### ISSUE TITLE
Warning: Peer dependencies set to Angular ^9.0.0 in ngx-ace-wrapper 10.0.0

### ISSUE THREAD

**Issue by appimpact** [zefoy/ngx-ace-wrapper#20]
![image](https://user-images.githubusercontent.com/34662138/89146968-a7a89080-d555-11ea-9714-2a673eb11421.png)

After we have upgraded to ngx-ace-wrapper 10.0.0, we are still getting an error that it has peer dependency on:
@angular/common ^9.0.0
@angular/core ^9.0.0

Seems that there is an error in package.json file that is distributed via npm:
![image](https://user-images.githubusercontent.com/34662138/89147208-4c2ad280-d556-11ea-83b9-86eda0d5fb68.png)

**Comment by sconix** [comment]
Thats normal, I do not think you need to care about the warning. I do not want to limit the Angular version to 10 since 9 works just as well.

**Comment by appimpact** [comment]
Can't you specify range instead?
Like this:
"@angular/core": ">9.0.0"

**Comment by sconix** [comment]
Ah true, I just now realized that I have been using ^ not >=. So my bad, will fix for next release :)
