### ISSUE TITLE
adding placeholder option

### ISSUE THREAD

**Issue by hopeng** [zefoy/ngx-ace-wrapper#32]
Hi, any chance we can have placeholder option added to the wrapper? It allows placeholder text to display when editor is empty.

```
var editor = ace.edit("editor");
editor.setOptions({
  mode: 'ace/mode/css',
  theme: 'ace/theme/cobalt',
  placeholder: "Enter CSS Code",
})
```

**Comment by sconix** [comment]
Not sure what was asked here, if ACE supports placeholder this already can be done so closing this.
