### ISSUE TITLE
Each 2 characters I write in the editor, the cursor goes back to the initial position (0,0).

### ISSUE THREAD

**Issue by blixit** [zefoy/ngx-ace-wrapper#4]
```
<ace *ngIf="file"
  style="display: block; flex-grow: 1; min-height:200px; height: 80vh !important"
  [config]="config"
  [mode]="'text'"
  [theme]="'github'"
  [(value)]="file.sourceCode"
></ace>
```
**file** is just an object with a field **sourceCode**.

Each 2 characters I write in the editor, the cursor goes back to the initial position (0,0).

The problem doesn't occur if I don't use double binding ( `[value]="file.sourceCode"`). But this way, I'm not able able to update my **file** object.
if use **onValueChange** like that (`(onValueChange)="file.sourceCode=$event"`) the problem occurs again. So I dont know what is the best way to bind the editor value with a variable.

Can you give me a working example ?

here is a little video to show the current behavior: https://share.vidyard.com/watch/fe8LnVunAy7YLLPvp9rEeB?

**Comment by sconix** [comment]
This seems to be a bug in the wrapper, its requesting the cursor to be on beginning after a change and not the end as it should. I will release a new version after I have verified the fix.

**Comment by blixit** [comment]
Thanks a lot !!
I will star and keep watching this project. Thanks to your wrapper I've been able to relaunch an old AngularJS project. I really appreciate the way you wrap Ace making it easy to use with Angular.
