### ISSUE TITLE
Access to editor programatically to add custom completer

### ISSUE THREAD

**Issue by SanderBreivik** [zefoy/ngx-ace-wrapper#43]
Hi!
How can I access the editor object? I want to add my own completer with a word list, to do this I have to do `editor.completers`. Or is there another way?

**Comment by Suraj-Gupta-ML** [comment]
@SanderBreivik did you get the editor instance access?

**Comment by fvassura** [comment]
Hi @SanderBreivik ,
I'm facing the same issue: cannot find `editor.completers` .
I have access to the editor instance (I use it to add commands) but still cannot figure out how to add custom copmleters.
How did you make it?
