### ISSUE TITLE
Cursor not aligned properly at the end

### ISSUE THREAD

**Issue by fvillarDev** [zefoy/ngx-ace-wrapper#7]
Hi, first of all, very nice wrapper! The issue appears in a Material Angular app, simple configuration, with either '_xml_' or '_sqlserver_' mode.
It looks like there are several 'spaces' after the text you are typing.

(notice the cursor at the end, I didn't add any space after)
![image](https://user-images.githubusercontent.com/8356080/61551571-ea232c00-aa2b-11e9-82fc-588e7f5f8845.png)

Any fix soon or how to workaround this?
Thanks!

**Comment by sconix** [comment]
This is just a wrapper so the issue is not in this library it must be in the Ace/Brace. You have checked that there is no styles leaking that could cause that?

**Comment by fvillarDev** [comment]
You were rigth @sconix .. its a library issue. I could fix this overriding some styles! Thanks!

**Comment by rgustavsson** [comment]
@fvillarDev how did you fix this on your end?
It used to work fine for me, until I upgraded from Angular 9 to 12.. Pulling my hair.. :)

**Comment by fvillarDev** [comment]
Its something related to the font (Angular is kinda overriding the ace css)
Try overriding this in css file:
```
.ace_keyword {
  font-family: monospace;
}

.ace_scroller div {
  font-family: monospace;
}

.ace_scroller span {
  font-family: monospace;
}

.ace-wrapper > * {
  font-family: monospace !important;
}
```

Monospace is what you need to fix the cursor position

Good luck!

**Comment by rgustavsson** [comment]
@fvillarDev my saviour - many thanks!
